# Form implementation generated from reading ui file 'pj.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from numpy import add
import soundfile as sf
from pedalboard import (
    Pedalboard,
    Convolution,
    Compressor,
    Chorus,
    Gain,
    Reverb,
    Limiter,
    LadderFilter,
    Phaser,
)
def add_effects():

    audio, sample_rate = sf.read('Take_Me_on.wav')

    # Make a Pedalboard object, containing multiple plugins:
    board = Pedalboard([
        Compressor(threshold_db=-50, ratio=25),
        Gain(gain_db=30),
        Chorus(),
        LadderFilter(mode=LadderFilter.Mode.HPF12, cutoff_hz=900),
        Phaser(),
        
        Reverb(room_size=0.25),
    ], sample_rate=sample_rate)

    # Pedalboard objects behave like lists, so you can add plugins:
    board.append(Compressor(threshold_db=-25, ratio=10))
    board.append(Gain(gain_db=10))
    board.append(Limiter())

    # Run the audio through this pedalboard!
    effected = board(audio)

    # Write the audio back as a wav file:
    with sf.SoundFile('./processed-output-stereo.wav', 'w', samplerate=sample_rate, channels=len(effected.shape)) as f:
        f.write(effected)

add_effects()
